// src/views/ab-test/app-manage.vue
<template>
  <WujieVue
    ref="wujieVueRef"
    width="100%"
    height="100%"
    name="app-manage"
    :url="props.url"
    :props="props"
    :plugins="[InstanceofPlugin()]"
  />
</template>

<script lang="ts" setup name="UserLabel">
// import { genCrowdParams } from '@cbd-wujie-components/osp-query'
import WujieVue from 'wujie-vue3'
import { InstanceofPlugin } from 'wujie-polyfill'
import { ref, onUnmounted } from 'vue'
import useUserStore from '@/store/modules/user'

const wujieVueRef = ref()

const { destroyApp } = WujieVue
const userStore = useUserStore()
const props = {
  groupId: userStore.groupId,
  brandId: userStore.brandId,
  brandName: userStore.brandName,
  token: userStore.token,
  // token: '1734320084|lctbxqrW6LJg4Llg.cAwqVORvOtZ2kdnHRRiDuj1Se5P/Hz+Vx9Ft/CNl+Hs=.dc8e3be96eea310d1',
  parentName: 'comm',
  url: userStore.env.abTestUrl,
  redirectUrl: '/app-manage',
}
console.log('人群洞察props：', props)
onUnmounted(() => {
  destroyApp('app-manage')
})
</script>

// src/views/ab-test/app-manage.svelte
<script lang="ts">
  import { KMessage } from '@ikun-ui/core'
  import WujieSvelte from '../../lib/wujie-svelte.svelte'
  import { InstanceofPlugin } from 'wujie-polyfill'
  const cache = localStorage.getItem('wujie-test-config') || '{}'
  const params = JSON.parse(cache)
  if (!params.env) {
    KMessage({
      content: '请点击设置，选择运行环境',
      type: 'warning',
      target: document.body,
    })
    params.env = {}
  }
  const props = {
    ...JSON.parse(cache),
    groupId: '267356',
    brandId: params.env.brandId,
    brandName: params.env.brandName,
    token: params.token,
    url: params.env.abTestUrl,
    parentName: 'comm',
    redirectUrl: '/app-manage',
  }
</script>
<WujieSvelte
        width="100%"
        height="100%"
        name="app-manage"
        url="{props.url}"
        props="{props}"
        plugins="{[InstanceofPlugin()]}">
</WujieSvelte>
